### PR TITLE
[BUGFIX] RDM Embolden to Manafication skipping Prefulgence

### LINKED ISSUE #494: [Bug] Red Mage - Embolden to Manafication
**Describe the bug**

Embolden to Manafication

Replace Embolden with Manafication if the former is on cooldown and the latter is not.

If Embolden is used and Manafication is off cooldown, it changes to Manafication. If Manafication is used, it changes to Vice of Thorns. If Vice of Thorns is used, it changes back to Embolden. I would expect it to change to Prefulgence when Prefulgence Ready is up, but this doesn't happen.

**To Reproduce**

Please try to submit as much information as possible to reproduce the behavior:

1. Which plugin version you have? v2.0.2.3
2. Which job is affected? RDM
3. What are your enabled combos for that job? Embolden to Manafication
4. Which skill is placed in your hotbar? Embolden
5. Are you using any other XIVCombo fork? No

**Expected behavior**

Replace Embolden with Manafication if the former is on cooldown and the latter is not or if Prefulgence Ready is up.

**Screenshots or videos**

n/a

**Additional context**

The game is currently down for maintenance, and plugins will probably be broken for awhile once it's back up. That said, I'm happy to provide more information as I'm able. I'm also happy to take a stab at this myself.

### PR DESCRIPTION
**Pull request by Starlight-alt**
Fixes #494.

Ensures combo into Vice of Thorns and Prefulgence actions (in that order of priority) after Embolden and Manafication are used and the readying buff is applied. Also shows unreadied Prefulgence while stacks of Manafication have yet to be consumed to indicate that should be readied soon.

Manafication will now not replace Embolden while out of combat, as it cannot be cast outside of combat.

### CODE REVIEW

File: XIVComboExpanded/Combos/RDM.cs [hunk 1]
```diff
@@ -426,8 +427,15 @@ protected override uint Invoke(uint actionID, uint lastComboMove, float comboTim
...
         {
-            if (level >= RDM.Levels.Manafication && IsCooldownUsable(RDM.Manafication) && !IsCooldownUsable(RDM.Embolden))
-                return RDM.Manafication;
+            if (level >= RDM.Levels.Manafication && !IsCooldownUsable(RDM.Embolden))
+            {
+                if (IsCooldownUsable(RDM.Manafication) && InCombat())
+                    return RDM.Manafication;
+                if (HasEffect(RDM.Buffs.ThornedFlourish))
+                    return RDM.ViceOfThorns;
+                if (HasEffect(RDM.Buffs.PrefulgenceReady) || HasEffect(RDM.Buffs.Manafication))
```
Comment (kaedys) [inline XIVComboExpanded/Combos/RDM.cs:436]: This will cause issues for RDMs below Prefulgence level.  Also, why is the OR condition here at all?

**Comment by MKhayle** [comment]
just fyi, my gpu fried recently and I can't do shit regarding this for now

**Comment by kaedys** [comment]
Oh no! 😭

**Comment by Starlight-alt** [comment]
Oof, that sucks, sorry @MKhayle . 😩
